apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '20'
    run.googleapis.com/urls: '["https://web-agency-ai-api-427643908968.asia-south1.run.app","https://web-agency-ai-api-g24zakxlza-el.a.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-south1
    run.googleapis.com/satisfiesPzs: 'true'
  name: web-agency-ai-api
  namespace: '427643908968'

spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 583.0.0
        run.googleapis.com/cloudsql-instances: web-agency-ai-508609:asia-south1:web-agency-postgres
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: rlmnwpnmsv
        run.googleapis.com/startupProbeType: Default

    spec:
      containerConcurrency: 80

      containers:
        - env:
            - name: HOST
              value: 0.0.0.0
            - name: DEBUG
              value: 'false'
            - name: CORS_ORIGINS
              value: '*'

            - name: ALIBABA_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: ALIBABA_KEY

            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: CLIENT_ID

            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: CLIENT_SECRET

            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: DATABASE_URI

            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_API_KEY

            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GROQ_API_KEY

            - name: HIVE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: HIVE_API_KEY

            - name: HUBSPOT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: HUBSPOT_CLIENT_ID

            - name: HUBSPOT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: HUBSPOT_CLIENT_SECRET

            - name: HUGGINGFACEHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: HUGGINGFACEHUB_API_TOKEN

            - name: LANGSMITH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: LANGSMITH_ENDPOINT

            - name: LANGSMITH_PROJECT
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: LANGSMITH_PROJECT

            - name: LANGSMITH_TRACING
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: LANGSMITH_TRACING

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: OPENAI_API_KEY

            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: OPENROUTER_API_KEY

            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: REFRESH_TOKEN

            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: TAVILY_API_KEY

            - name: GOOGLE_CALENDAR_MCP_TOKEN_PATH
              value: /app/google-calendar-tokens/tokens.json

            - name: GOOGLE_OAUTH_CREDENTIALS
              value: /etc/google-calendar/gcp-oauth.keys.json

            - name: HUBSPOT_TOKEN_FILE
              value: /app/hubspot-tokens/hubspot_tokens.json

            - name: CONFIG_REFRESH
              value: 20260915-2

          image: asia-south1-docker.pkg.dev/web-agency-ai-508609/web-agency-ai/api@sha256:52d2f1bc0596adda36045504980eee76343f9fb467927d60819c688df2045a25

          ports:
            - containerPort: 8080
              name: http1

          resources:
            limits:
              cpu: '1'
              memory: 1Gi

          startupProbe:
            failureThreshold: 1
            periodSeconds: 240
            tcpSocket:
              port: 8080
            timeoutSeconds: 240

          volumeMounts:
            - mountPath: /app/google-calendar-tokens
              name: cloud-storage-xok-lin

            - mountPath: /etc/google-calendar
              name: GOOGLE_CALENDAR_OAUTH_CREDENTIALS-xar-bag

            - mountPath: /app/hubspot-tokens
              name: cloud-storage-ros-wed

            - mountPath: /cloudsql
              name: cloudsql

      serviceAccountName: 427643908968-compute@developer.gserviceaccount.com

      timeoutSeconds: 3600

      volumes:
        - csi:
            driver: gcsfuse.run.googleapis.com
            volumeAttributes:
              bucketName: web-agency-ai-calendar-tokens-508609-2026
          name: cloud-storage-xok-lin

        - name: GOOGLE_CALENDAR_OAUTH_CREDENTIALS-xar-bag
          secret:
            items:
              - key: latest
                path: gcp-oauth.keys.json
            secretName: GOOGLE_CALENDAR_OAUTH_CREDENTIALS

        - csi:
            driver: gcsfuse.run.googleapis.com
            volumeAttributes:
              bucketName: web-agency-ai-hubspot-tokens-508609-2026
          name: cloud-storage-ros-wed

        - name: cloudsql
          cloudSql:
            instances:
              - web-agency-ai-508609:asia-south1:web-agency-postgres

  traffic:
    - latestRevision: true
      percent: 100